name: golang_dev

services:
  db:
    image: postgres:16
    env_file:
      - app.env
    environment:
      POSTGRES_DB: development_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: development_user
    volumes:
      - ../golang_volumes/pgsql_volumes/golang_dev/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U development_user"]
      interval: 10s
      timeout: 5s
      retries: 2

  redis:
    image: redis:latest
    volumes:
      - ../golang_volumes/redis_volumes/golang_dev/:/data

  backend:
    image: golang_dev:latest
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - app.env

  nginx:
    image: nginx:latest
    depends_on:
      - backend
    ports:
      - "7000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
